---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - auth0.gracey.io
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth0.gracey.io
  resources:
  - clients/finalizers
  verbs:
  - update
- apiGroups:
  - auth0.gracey.io
  resources:
  - clients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - auth0.gracey.io
  resources:
  - events
  verbs:
  - create
  - patch
